language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=5286fe366f9880c571dcdfe0d7748a6343eb7eb0788250626df792cd3120ab87
    - SAUCE_USERNAME=nomego
    - secure: j1R1meQnv2Gc9nk1v76q2DbDf1vThlA1DW/8fhySdit19/vESnn2bVPKlcnQA5AOsqgkR/lmcsOWaWV1FU4CD6jn6AWesRjLjYkZrqt+aXZ/l1dHTjrf0O9bF6zgif4lzAgwJCu5ADfRZYhrHX+jipqB/Elxl9UE95EXEs6XeCJbDtaUjamYlEnMAeoS188bs15BEudR+xRTggRBjFGRIhqKKGZ/vyGTK+0G0G9I8utgi2kF2zI8vypw2LgW+k2dcihl7vm4GsjfDFv+9toCzMw43nnMPE2Co/uoPDp9oqnW0NUdHjmY6b/RGX2IfJBEr6klOnCFbJHB67ERgYsuWybIlLJQA9ImSquYjw5R/VQ/Tpk7WZaeT7Q8Vbo2zHMVU2tmOyGzewXGHdvctSOAgB6Ky/53pmCNln2FT4QkyKZxQH3B0WlLdEWtiTMLf7k+yOlIgZ87/sMSnjd5SA2KjcCqK/3CHfBWZju6RbrjuAg0od/HOxFvpx7zz5vJI+RKL7wcD3Unz0BaL3Y6Ci8PJSTxqhl4L3rZXkUDxnLaET6shnxnrVBczrjaLbM+xh8K3utammZIzVmdyTXkR1FDqds2h+obxGZvdaIP574/UaC4j6lbFFLJ2fR/0hlQenifKnGhF9sW2FmH/69G8klKoE0mUHW5463m0/D0j4M0uPE=
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - ".eslintcache"
    - "$HOME/.cache/bower"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn run lint
script:
  - yarn test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: h7CJKsyJdZstrUUBuyRbWpXVpT5ZrDR8cnsRSoAWbpC37y7FQTtUR/70umVGphm5JlRuwxxeg2WASjgaToIYuwb/1G2CnwuVfitNl/SyxwAmyeFLkdmpG2VoV0PYs475x2Ta24tmSojAwmJhuHdVPE5SMyUdxcUcQpvfkHIlo9hizdfvdHMru38eDZBjnx8FDAX9a79qEtUDkUoN79GsoyO4qqxUjXqpMoY64OonyhIslgHbJmd+jUaTCnD9WqhS2PH6h0NBW2U/jw2G5hvWUDyex65I6PV6YAQt58bNH7yf+o+pkTDlq675LqrJZ1Wcf30U9QZiR74Su2bv6xUiY1pbnzf8MMV/mwKYKFU1MpNE/FV5JXhTMN3RYJ4udQ4weQVKoEob4wS7XYgrjBNJ9Wkl+Je+H1PgiYHAHEb5RVzVDtznSMqWBu/I13/sEj10JIJwEZMXtuZmRT1Kyatkhl38PKldPSQtR7H8rvT+tUeUvlDRWt3kpBwOPsiK5/XEDmxlu2TtMnX+MMARCNPfP/Z23dkHCPAdK3Sjc+IatZECOKFYH1Km2p8lnBEIrCKgFMqQH9WqUaM9DMaLVzHqP3S5NkuYYQUvBOQCM9tw/1115Z2AHTq1lR1oXBPO+RTFo/UL0S3ohw3UD+u+j53DOpLDIJjgp8NTvpjkTeeLiks=
